/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdExportRouteImport } from './routes/projects.$projectId.export'
import { Route as ProjectsProjectIdImportRouteImport } from './routes/projects.$projectId.import'
import { Route as ProjectsProjectIdLocalesRouteImport } from './routes/projects.$projectId.locales'
import { Route as ProjectsProjectIdProposalsRouteImport } from './routes/projects.$projectId.proposals'
import { Route as ProjectsProjectIdReleaseRouteImport } from './routes/projects.$projectId.release'
import { Route as ProjectsProjectIdReviewsRouteImport } from './routes/projects.$projectId.reviews'
import { Route as ProjectsProjectIdScreensRouteImport } from './routes/projects.$projectId.screens'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdStringsRouteImport } from './routes/projects.$projectId.strings'
import { Route as ProjectsProjectIdSyncRouteImport } from './routes/projects.$projectId.sync'
import { Route as ProjectsProjectIdTagsRouteImport } from './routes/projects.$projectId.tags'
import { Route as ProjectsProjectIdLocaleProposalsPtRouteImport } from './routes/projects.$projectId.locale-proposals.pt'
import { Route as ProjectsProjectIdProposalsIndexRouteImport } from './routes/projects.$projectId.proposals.index'
import { Route as ProjectsProjectIdProposalsProposalIdRouteImport } from './routes/projects.$projectId.proposals.$proposalId'
import { Route as ProjectsProjectIdReviewsIndexRouteImport } from './routes/projects.$projectId.reviews.index'
import { Route as ProjectsProjectIdReviewsChangeSetIdRouteImport } from './routes/projects.$projectId.reviews.$changeSetId'
import { Route as ProjectsProjectIdSettingsApiTokensRouteImport } from './routes/projects.$projectId.settings.api-tokens'
import { Route as ProjectsProjectIdSettingsGuidanceRouteImport } from './routes/projects.$projectId.settings.guidance'
import { Route as ProjectsProjectIdSettingsLanguagesRouteImport } from './routes/projects.$projectId.settings.languages'
import { Route as ProjectsProjectIdSettingsMembersRouteImport } from './routes/projects.$projectId.settings.members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdExportRoute = ProjectsProjectIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdImportRoute = ProjectsProjectIdImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdLocalesRoute =
  ProjectsProjectIdLocalesRouteImport.update({
    id: '/locales',
    path: '/locales',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdProposalsRoute =
  ProjectsProjectIdProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdReleaseRoute =
  ProjectsProjectIdReleaseRouteImport.update({
    id: '/release',
    path: '/release',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdReviewsRoute =
  ProjectsProjectIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdScreensRoute =
  ProjectsProjectIdScreensRouteImport.update({
    id: '/screens',
    path: '/screens',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdStringsRoute =
  ProjectsProjectIdStringsRouteImport.update({
    id: '/strings',
    path: '/strings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSyncRoute = ProjectsProjectIdSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTagsRoute = ProjectsProjectIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdLocaleProposalsPtRoute =
  ProjectsProjectIdLocaleProposalsPtRouteImport.update({
    id: '/locale-proposals/pt',
    path: '/locale-proposals/pt',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdProposalsIndexRoute =
  ProjectsProjectIdProposalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdProposalsRoute,
  } as any)
const ProjectsProjectIdProposalsProposalIdRoute =
  ProjectsProjectIdProposalsProposalIdRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => ProjectsProjectIdProposalsRoute,
  } as any)
const ProjectsProjectIdReviewsIndexRoute =
  ProjectsProjectIdReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdReviewsRoute,
  } as any)
const ProjectsProjectIdReviewsChangeSetIdRoute =
  ProjectsProjectIdReviewsChangeSetIdRouteImport.update({
    id: '/$changeSetId',
    path: '/$changeSetId',
    getParentRoute: () => ProjectsProjectIdReviewsRoute,
  } as any)
const ProjectsProjectIdSettingsApiTokensRoute =
  ProjectsProjectIdSettingsApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)
const ProjectsProjectIdSettingsGuidanceRoute =
  ProjectsProjectIdSettingsGuidanceRouteImport.update({
    id: '/guidance',
    path: '/guidance',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)
const ProjectsProjectIdSettingsLanguagesRoute =
  ProjectsProjectIdSettingsLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)
const ProjectsProjectIdSettingsMembersRoute =
  ProjectsProjectIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/import': typeof ProjectsProjectIdImportRoute
  '/projects/$projectId/locales': typeof ProjectsProjectIdLocalesRoute
  '/projects/$projectId/proposals': typeof ProjectsProjectIdProposalsRouteWithChildren
  '/projects/$projectId/release': typeof ProjectsProjectIdReleaseRoute
  '/projects/$projectId/reviews': typeof ProjectsProjectIdReviewsRouteWithChildren
  '/projects/$projectId/screens': typeof ProjectsProjectIdScreensRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/sync': typeof ProjectsProjectIdSyncRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/locale-proposals/pt': typeof ProjectsProjectIdLocaleProposalsPtRoute
  '/projects/$projectId/proposals/$proposalId': typeof ProjectsProjectIdProposalsProposalIdRoute
  '/projects/$projectId/reviews/$changeSetId': typeof ProjectsProjectIdReviewsChangeSetIdRoute
  '/projects/$projectId/settings/api-tokens': typeof ProjectsProjectIdSettingsApiTokensRoute
  '/projects/$projectId/settings/guidance': typeof ProjectsProjectIdSettingsGuidanceRoute
  '/projects/$projectId/settings/languages': typeof ProjectsProjectIdSettingsLanguagesRoute
  '/projects/$projectId/settings/members': typeof ProjectsProjectIdSettingsMembersRoute
  '/projects/$projectId/proposals/': typeof ProjectsProjectIdProposalsIndexRoute
  '/projects/$projectId/reviews/': typeof ProjectsProjectIdReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/import': typeof ProjectsProjectIdImportRoute
  '/projects/$projectId/locales': typeof ProjectsProjectIdLocalesRoute
  '/projects/$projectId/release': typeof ProjectsProjectIdReleaseRoute
  '/projects/$projectId/screens': typeof ProjectsProjectIdScreensRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/sync': typeof ProjectsProjectIdSyncRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/locale-proposals/pt': typeof ProjectsProjectIdLocaleProposalsPtRoute
  '/projects/$projectId/proposals/$proposalId': typeof ProjectsProjectIdProposalsProposalIdRoute
  '/projects/$projectId/reviews/$changeSetId': typeof ProjectsProjectIdReviewsChangeSetIdRoute
  '/projects/$projectId/settings/api-tokens': typeof ProjectsProjectIdSettingsApiTokensRoute
  '/projects/$projectId/settings/guidance': typeof ProjectsProjectIdSettingsGuidanceRoute
  '/projects/$projectId/settings/languages': typeof ProjectsProjectIdSettingsLanguagesRoute
  '/projects/$projectId/settings/members': typeof ProjectsProjectIdSettingsMembersRoute
  '/projects/$projectId/proposals': typeof ProjectsProjectIdProposalsIndexRoute
  '/projects/$projectId/reviews': typeof ProjectsProjectIdReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/import': typeof ProjectsProjectIdImportRoute
  '/projects/$projectId/locales': typeof ProjectsProjectIdLocalesRoute
  '/projects/$projectId/proposals': typeof ProjectsProjectIdProposalsRouteWithChildren
  '/projects/$projectId/release': typeof ProjectsProjectIdReleaseRoute
  '/projects/$projectId/reviews': typeof ProjectsProjectIdReviewsRouteWithChildren
  '/projects/$projectId/screens': typeof ProjectsProjectIdScreensRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/sync': typeof ProjectsProjectIdSyncRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/locale-proposals/pt': typeof ProjectsProjectIdLocaleProposalsPtRoute
  '/projects/$projectId/proposals/$proposalId': typeof ProjectsProjectIdProposalsProposalIdRoute
  '/projects/$projectId/reviews/$changeSetId': typeof ProjectsProjectIdReviewsChangeSetIdRoute
  '/projects/$projectId/settings/api-tokens': typeof ProjectsProjectIdSettingsApiTokensRoute
  '/projects/$projectId/settings/guidance': typeof ProjectsProjectIdSettingsGuidanceRoute
  '/projects/$projectId/settings/languages': typeof ProjectsProjectIdSettingsLanguagesRoute
  '/projects/$projectId/settings/members': typeof ProjectsProjectIdSettingsMembersRoute
  '/projects/$projectId/proposals/': typeof ProjectsProjectIdProposalsIndexRoute
  '/projects/$projectId/reviews/': typeof ProjectsProjectIdReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/reset-password'
    | '/sign-in'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/export'
    | '/projects/$projectId/import'
    | '/projects/$projectId/locales'
    | '/projects/$projectId/proposals'
    | '/projects/$projectId/release'
    | '/projects/$projectId/reviews'
    | '/projects/$projectId/screens'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/sync'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/locale-proposals/pt'
    | '/projects/$projectId/proposals/$proposalId'
    | '/projects/$projectId/reviews/$changeSetId'
    | '/projects/$projectId/settings/api-tokens'
    | '/projects/$projectId/settings/guidance'
    | '/projects/$projectId/settings/languages'
    | '/projects/$projectId/settings/members'
    | '/projects/$projectId/proposals/'
    | '/projects/$projectId/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/reset-password'
    | '/sign-in'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/export'
    | '/projects/$projectId/import'
    | '/projects/$projectId/locales'
    | '/projects/$projectId/release'
    | '/projects/$projectId/screens'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/sync'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/locale-proposals/pt'
    | '/projects/$projectId/proposals/$proposalId'
    | '/projects/$projectId/reviews/$changeSetId'
    | '/projects/$projectId/settings/api-tokens'
    | '/projects/$projectId/settings/guidance'
    | '/projects/$projectId/settings/languages'
    | '/projects/$projectId/settings/members'
    | '/projects/$projectId/proposals'
    | '/projects/$projectId/reviews'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/projects'
    | '/reset-password'
    | '/sign-in'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/export'
    | '/projects/$projectId/import'
    | '/projects/$projectId/locales'
    | '/projects/$projectId/proposals'
    | '/projects/$projectId/release'
    | '/projects/$projectId/reviews'
    | '/projects/$projectId/screens'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/sync'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/locale-proposals/pt'
    | '/projects/$projectId/proposals/$proposalId'
    | '/projects/$projectId/reviews/$changeSetId'
    | '/projects/$projectId/settings/api-tokens'
    | '/projects/$projectId/settings/guidance'
    | '/projects/$projectId/settings/languages'
    | '/projects/$projectId/settings/members'
    | '/projects/$projectId/proposals/'
    | '/projects/$projectId/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/export': {
      id: '/projects/$projectId/export'
      path: '/export'
      fullPath: '/projects/$projectId/export'
      preLoaderRoute: typeof ProjectsProjectIdExportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/import': {
      id: '/projects/$projectId/import'
      path: '/import'
      fullPath: '/projects/$projectId/import'
      preLoaderRoute: typeof ProjectsProjectIdImportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/locales': {
      id: '/projects/$projectId/locales'
      path: '/locales'
      fullPath: '/projects/$projectId/locales'
      preLoaderRoute: typeof ProjectsProjectIdLocalesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/proposals': {
      id: '/projects/$projectId/proposals'
      path: '/proposals'
      fullPath: '/projects/$projectId/proposals'
      preLoaderRoute: typeof ProjectsProjectIdProposalsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/release': {
      id: '/projects/$projectId/release'
      path: '/release'
      fullPath: '/projects/$projectId/release'
      preLoaderRoute: typeof ProjectsProjectIdReleaseRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/reviews': {
      id: '/projects/$projectId/reviews'
      path: '/reviews'
      fullPath: '/projects/$projectId/reviews'
      preLoaderRoute: typeof ProjectsProjectIdReviewsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/screens': {
      id: '/projects/$projectId/screens'
      path: '/screens'
      fullPath: '/projects/$projectId/screens'
      preLoaderRoute: typeof ProjectsProjectIdScreensRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/strings': {
      id: '/projects/$projectId/strings'
      path: '/strings'
      fullPath: '/projects/$projectId/strings'
      preLoaderRoute: typeof ProjectsProjectIdStringsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/sync': {
      id: '/projects/$projectId/sync'
      path: '/sync'
      fullPath: '/projects/$projectId/sync'
      preLoaderRoute: typeof ProjectsProjectIdSyncRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tags': {
      id: '/projects/$projectId/tags'
      path: '/tags'
      fullPath: '/projects/$projectId/tags'
      preLoaderRoute: typeof ProjectsProjectIdTagsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/locale-proposals/pt': {
      id: '/projects/$projectId/locale-proposals/pt'
      path: '/locale-proposals/pt'
      fullPath: '/projects/$projectId/locale-proposals/pt'
      preLoaderRoute: typeof ProjectsProjectIdLocaleProposalsPtRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/proposals/': {
      id: '/projects/$projectId/proposals/'
      path: '/'
      fullPath: '/projects/$projectId/proposals/'
      preLoaderRoute: typeof ProjectsProjectIdProposalsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdProposalsRoute
    }
    '/projects/$projectId/proposals/$proposalId': {
      id: '/projects/$projectId/proposals/$proposalId'
      path: '/$proposalId'
      fullPath: '/projects/$projectId/proposals/$proposalId'
      preLoaderRoute: typeof ProjectsProjectIdProposalsProposalIdRouteImport
      parentRoute: typeof ProjectsProjectIdProposalsRoute
    }
    '/projects/$projectId/reviews/': {
      id: '/projects/$projectId/reviews/'
      path: '/'
      fullPath: '/projects/$projectId/reviews/'
      preLoaderRoute: typeof ProjectsProjectIdReviewsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdReviewsRoute
    }
    '/projects/$projectId/reviews/$changeSetId': {
      id: '/projects/$projectId/reviews/$changeSetId'
      path: '/$changeSetId'
      fullPath: '/projects/$projectId/reviews/$changeSetId'
      preLoaderRoute: typeof ProjectsProjectIdReviewsChangeSetIdRouteImport
      parentRoute: typeof ProjectsProjectIdReviewsRoute
    }
    '/projects/$projectId/settings/api-tokens': {
      id: '/projects/$projectId/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/projects/$projectId/settings/api-tokens'
      preLoaderRoute: typeof ProjectsProjectIdSettingsApiTokensRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRoute
    }
    '/projects/$projectId/settings/guidance': {
      id: '/projects/$projectId/settings/guidance'
      path: '/guidance'
      fullPath: '/projects/$projectId/settings/guidance'
      preLoaderRoute: typeof ProjectsProjectIdSettingsGuidanceRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRoute
    }
    '/projects/$projectId/settings/languages': {
      id: '/projects/$projectId/settings/languages'
      path: '/languages'
      fullPath: '/projects/$projectId/settings/languages'
      preLoaderRoute: typeof ProjectsProjectIdSettingsLanguagesRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRoute
    }
    '/projects/$projectId/settings/members': {
      id: '/projects/$projectId/settings/members'
      path: '/members'
      fullPath: '/projects/$projectId/settings/members'
      preLoaderRoute: typeof ProjectsProjectIdSettingsMembersRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRoute
    }
  }
}

interface ProjectsProjectIdProposalsRouteChildren {
  ProjectsProjectIdProposalsProposalIdRoute: typeof ProjectsProjectIdProposalsProposalIdRoute
  ProjectsProjectIdProposalsIndexRoute: typeof ProjectsProjectIdProposalsIndexRoute
}

const ProjectsProjectIdProposalsRouteChildren: ProjectsProjectIdProposalsRouteChildren =
  {
    ProjectsProjectIdProposalsProposalIdRoute:
      ProjectsProjectIdProposalsProposalIdRoute,
    ProjectsProjectIdProposalsIndexRoute: ProjectsProjectIdProposalsIndexRoute,
  }

const ProjectsProjectIdProposalsRouteWithChildren =
  ProjectsProjectIdProposalsRoute._addFileChildren(
    ProjectsProjectIdProposalsRouteChildren,
  )

interface ProjectsProjectIdReviewsRouteChildren {
  ProjectsProjectIdReviewsChangeSetIdRoute: typeof ProjectsProjectIdReviewsChangeSetIdRoute
  ProjectsProjectIdReviewsIndexRoute: typeof ProjectsProjectIdReviewsIndexRoute
}

const ProjectsProjectIdReviewsRouteChildren: ProjectsProjectIdReviewsRouteChildren =
  {
    ProjectsProjectIdReviewsChangeSetIdRoute:
      ProjectsProjectIdReviewsChangeSetIdRoute,
    ProjectsProjectIdReviewsIndexRoute: ProjectsProjectIdReviewsIndexRoute,
  }

const ProjectsProjectIdReviewsRouteWithChildren =
  ProjectsProjectIdReviewsRoute._addFileChildren(
    ProjectsProjectIdReviewsRouteChildren,
  )

interface ProjectsProjectIdSettingsRouteChildren {
  ProjectsProjectIdSettingsApiTokensRoute: typeof ProjectsProjectIdSettingsApiTokensRoute
  ProjectsProjectIdSettingsGuidanceRoute: typeof ProjectsProjectIdSettingsGuidanceRoute
  ProjectsProjectIdSettingsLanguagesRoute: typeof ProjectsProjectIdSettingsLanguagesRoute
  ProjectsProjectIdSettingsMembersRoute: typeof ProjectsProjectIdSettingsMembersRoute
}

const ProjectsProjectIdSettingsRouteChildren: ProjectsProjectIdSettingsRouteChildren =
  {
    ProjectsProjectIdSettingsApiTokensRoute:
      ProjectsProjectIdSettingsApiTokensRoute,
    ProjectsProjectIdSettingsGuidanceRoute:
      ProjectsProjectIdSettingsGuidanceRoute,
    ProjectsProjectIdSettingsLanguagesRoute:
      ProjectsProjectIdSettingsLanguagesRoute,
    ProjectsProjectIdSettingsMembersRoute:
      ProjectsProjectIdSettingsMembersRoute,
  }

const ProjectsProjectIdSettingsRouteWithChildren =
  ProjectsProjectIdSettingsRoute._addFileChildren(
    ProjectsProjectIdSettingsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdExportRoute: typeof ProjectsProjectIdExportRoute
  ProjectsProjectIdImportRoute: typeof ProjectsProjectIdImportRoute
  ProjectsProjectIdLocalesRoute: typeof ProjectsProjectIdLocalesRoute
  ProjectsProjectIdProposalsRoute: typeof ProjectsProjectIdProposalsRouteWithChildren
  ProjectsProjectIdReleaseRoute: typeof ProjectsProjectIdReleaseRoute
  ProjectsProjectIdReviewsRoute: typeof ProjectsProjectIdReviewsRouteWithChildren
  ProjectsProjectIdScreensRoute: typeof ProjectsProjectIdScreensRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRouteWithChildren
  ProjectsProjectIdStringsRoute: typeof ProjectsProjectIdStringsRoute
  ProjectsProjectIdSyncRoute: typeof ProjectsProjectIdSyncRoute
  ProjectsProjectIdTagsRoute: typeof ProjectsProjectIdTagsRoute
  ProjectsProjectIdLocaleProposalsPtRoute: typeof ProjectsProjectIdLocaleProposalsPtRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdExportRoute: ProjectsProjectIdExportRoute,
  ProjectsProjectIdImportRoute: ProjectsProjectIdImportRoute,
  ProjectsProjectIdLocalesRoute: ProjectsProjectIdLocalesRoute,
  ProjectsProjectIdProposalsRoute: ProjectsProjectIdProposalsRouteWithChildren,
  ProjectsProjectIdReleaseRoute: ProjectsProjectIdReleaseRoute,
  ProjectsProjectIdReviewsRoute: ProjectsProjectIdReviewsRouteWithChildren,
  ProjectsProjectIdScreensRoute: ProjectsProjectIdScreensRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRouteWithChildren,
  ProjectsProjectIdStringsRoute: ProjectsProjectIdStringsRoute,
  ProjectsProjectIdSyncRoute: ProjectsProjectIdSyncRoute,
  ProjectsProjectIdTagsRoute: ProjectsProjectIdTagsRoute,
  ProjectsProjectIdLocaleProposalsPtRoute:
    ProjectsProjectIdLocaleProposalsPtRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
